import type { PatientEncounter } from '../types';
import { generateFhirR4Bundle } from '../services/fhirConverter';
import { SAMPLE_DOCUMENTS, parseDocumentScan } from '../services/documentAi';

export const INITIAL_PATIENTS: PatientEncounter[] = [
  {
    id: 'enc-2026-001',
    kioskId: 'KIOSK_AIIMS_DELHI_01',
    mode: 'ALLOPATHIC',
    language: 'hi',
    createdAt: '2026-09-08T09:15:00Z',
    status: 'EMERGENCY_ESCALATED',
    patient: {
      abhaNumber: '91-4829-1029-4481',
      abhaAddress: 'ramesh.kumar94@abdm',
      name: 'Ramesh Kumar',
      gender: 'MALE',
      age: 54,
      dob: '1972-04-14',
      mobile: '+91 98765 43210',
      pinCode: '110029',
      state: 'Delhi',
      district: 'South Delhi',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      authMethod: 'QR_SCAN',
      verified: true,
      queueToken: 'EMERG-P1-4091',
      queueNumber: 1,
      registeredAt: '2026-09-08T09:15:00Z',
    },
    redFlag: {
      isTriggered: true,
      level: 'CRITICAL',
      triagePriority: 'P1_EMERGENCY',
      triggeredRules: [
        'ACS Rule #1: Potential Acute Myocardial Infarction (Crushing retrosternal chest pain with left arm radiation & sweating)',
      ],
      immediateAction:
        '🚨 IMMEDIATE ACTION: Escort patient to Emergency Resuscitation Room / Triage Desk 1. Initiate 12-lead ECG, IV Access, and high-flow Oxygen.',
      emergencyTokenCode: 'EMERG-P1-4091',
      timestamp: '2026-09-08T09:18:22Z',
      acknowledgedByDoctor: false,
    },
    socrates: {
      site: 'Central Chest (Retrosternal)',
      onset: 'Sudden onset 90 minutes ago while walking up stairs',
      character: 'Crushing / Heavy pressure like a band tightening',
      radiation: 'Radiates directly to left shoulder, inner left arm and lower jaw',
      associations: ['Profuse cold sweating', 'Shortness of breath (Dyspnea)', 'Nausea', 'Lightheadedness'],
      timeCourse: 'Continuous and worsening over the last 30 minutes',
      exacerbatingRelieving: 'Worse with minimal physical exertion, no relief with resting',
      severity: 9,
      severityDescription: 'Severe / Excruciating (Score: 9/10)',
      reviewOfSystems: {
        cardiovascular: 'Positive for angina, diaphoresis, palpitation sensation',
        respiratory: 'Dyspnea on exertion, orthopnea',
        gastrointestinal: 'Mild epigastric nausea, no vomiting',
      },
    },
    scannedDocuments: [parseDocumentScan('doc-rx-cardio-01')],
    soapNote: {
      subjective: {
        chiefComplaint: 'Acute crushing central chest pain radiating to left arm with profuse sweating for 1.5 hours.',
        historyOfPresentIllness:
          '54-year-old male hypertensive and dyslipidemic patient presented via ABHA Kiosk with sudden-onset heavy retrosternal chest tightness (VAS 9/10) radiating to left arm and jaw. Accompanied by cold diaphoresis and grade III dyspnea. Has known CAD on Ecosprin and Atorvastatin.',
        pastMedicalHistory: ['Hypertension (7 years)', 'Dyslipidemia (4 years)', 'Chronic Stable Angina'],
        medicationHistory: ['Tab Ecosprin 75mg OD', 'Tab Atorva 20mg HS', 'Tab Metolar XR 50mg OD', 'Tab Sorbitrate 5mg SOS'],
        allergies: ['Penicillin (Maculopapular rash)'],
        familyHistory: 'Father had fatal MI at age 58.',
        socialHabits: 'Non-smoker, occasional alcohol.',
      },
      objective: {
        vitals: {
          bpSystolic: 154,
          bpDiastolic: 98,
          pulseRate: 104,
          spo2: 94,
          tempF: 98.4,
          respiratoryRate: 24,
          painScore: 9,
          bmi: 27.2,
        },
        physicalExamFindings: [
          'Patient in acute distress, pale, clammy and diaphoretic',
          'S1, S2 present, tachycardic, no obvious murmurs',
          'Bilateral basal fine crepitations on lung auscultation',
        ],
        extractedLabHighlights: [],
        digitizedPastRx: SAMPLE_DOCUMENTS[0].meds,
      },
      assessment: {
        provisionalDiagnoses: [
          {
            condition: 'Acute Coronary Syndrome - Suspected STEMI / NSTEMI',
            icd10: 'I21.9',
            snomedCt: '401303003',
            confidence: 0.94,
            rationale: 'Classic SOCRATES crushing retrosternal pain with left arm radiation, diaphoresis and autonomic signs in patient with CAD risk factors.',
          },
          {
            condition: 'Hypertensive Urgency',
            icd10: 'I10',
            snomedCt: '38341003',
            confidence: 0.88,
            rationale: 'Blood pressure elevated at 154/98 mmHg secondary to sympathetic surge.',
          },
        ],
        redFlagsIdentified: ['Crushing chest pain radiating to left arm', 'Cold diaphoresis', 'Tachycardia & Dyspnea'],
        clinicalRiskRating: 'HIGH',
      },
      plan: {
        proposedInvestigations: [
          'Stat 12-Lead Electrocardiogram (ECG)',
          'Stat High-Sensitivity Cardiac Troponin-I (hs-cTnI)',
          'Point-of-Care Echocardiography (Bedside 2D Echo)',
          'Complete Hemogram & Serum Electrolytes',
        ],
        medicationRecommendations: [
          {
            name: 'Tab Aspirin (Soluble/Chewable)',
            dosage: '300 mg',
            frequency: 'Stat (Immediate)',
            duration: 'Single dose',
            instructions: 'Chew immediately under ER nurse supervision',
            category: 'Allopathic',
          },
          {
            name: 'Tab Clopidogrel (Loading dose)',
            dosage: '300 mg',
            frequency: 'Stat (Immediate)',
            duration: 'Single dose',
            instructions: 'Administer orally stat in triage',
            category: 'Allopathic',
          },
          {
            name: 'Tab Atorvastatin (High intensity)',
            dosage: '80 mg',
            frequency: 'Stat',
            duration: 'Single dose',
            instructions: 'Immediate stat loading dose',
            category: 'Allopathic',
          },
          {
            name: 'Sublingual Nitroglycerin spray/tab',
            dosage: '0.4 mg',
            frequency: 'SOS',
            duration: 'Every 5 mins x 3',
            instructions: 'Monitor BP continuously before giving',
            category: 'Allopathic',
          },
        ],
        lifestyleAndDietAdvice: ['Strict bed rest', 'Continuous Cardiac Telemetry monitoring', 'NPO pending urgent angiography'],
        triageDisposition: 'Direct Transfer to Cardiac Cath Lab / Intensive Cardiac Care Unit (ICCU)',
        followUpInDays: 0,
      },
      metadata: {
        generatedAt: '2026-09-08T09:18:00Z',
        modelVersion: 'Med-Llama-3-8B-Indic + LangGraph Triage v3.1',
        mode: 'ALLOPATHIC',
        safetyLock: 'AI-Generated Triage Summary — Requires Clinician Verification',
        status: 'AI_DRAFT',
      },
    },
    fhirBundle: {},
  },
  {
    id: 'enc-2026-002',
    kioskId: 'KIOSK_AIIMS_DELHI_02',
    mode: 'ALLOPATHIC',
    language: 'hi',
    createdAt: '2026-09-08T09:30:00Z',
    status: 'WAITING',
    patient: {
      abhaNumber: '14-8921-3940-5912',
      abhaAddress: 'sunita.devi51@abdm',
      name: 'Sunita Devi',
      gender: 'FEMALE',
      age: 51,
      dob: '1975-08-20',
      mobile: '+91 94150 11223',
      pinCode: '226001',
      state: 'Uttar Pradesh',
      district: 'Lucknow',
      photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
      authMethod: 'MOBILE_OTP',
      verified: true,
      queueToken: 'URG-P2-8192',
      queueNumber: 2,
      registeredAt: '2026-09-08T09:30:00Z',
    },
    redFlag: {
      isTriggered: true,
      level: 'WARNING',
      triagePriority: 'P2_URGENT',
      triggeredRules: ['Uncontrolled Hyperglycemia (HbA1c 9.4%, Fasting Glucose 194 mg/dL) with elevated Serum Creatinine (1.8 mg/dL)'],
      immediateAction: '⚠️ PRIORITY ACTION: Fast-track to Nephrology / Endocrinology OPD desk. Urine dipstick for microalbuminuria required.',
      emergencyTokenCode: 'URG-P2-8192',
      timestamp: '2026-09-08T09:33:10Z',
      acknowledgedByDoctor: false,
    },
    socrates: {
      site: 'Bilateral Lower Limbs & Epigastrium',
      onset: 'Burning foot sensation worsening over 4 months; fatigue for 6 months',
      character: 'Tingling, burning numbness ("pins and needles") with early morning nausea',
      radiation: 'Ascending from soles of feet up to mid-calf bilaterally',
      associations: ['Polydipsia (excessive thirst)', 'Polyuria (waking 4 times at night to urinate)', 'Blurring of vision', 'Bilateral pedal edema'],
      timeCourse: 'Gradually progressive',
      exacerbatingRelieving: 'Burning worse at night and during sleep',
      severity: 6,
      severityDescription: 'Moderate to High (Score: 6/10)',
      reviewOfSystems: {
        neurological: 'Distal symmetrical sensorimotor polyneuropathy symptoms',
        gastrointestinal: 'Early satiety, post-prandial fullness (possible gastroparesis)',
        musculoskeletal: 'Mild bilateral pitting ankle edema',
      },
    },
    scannedDocuments: [parseDocumentScan('doc-lab-metabolic-02')],
    soapNote: {
      subjective: {
        chiefComplaint: 'Severe burning sensation in both feet, excessive thirst, and chronic fatigue for 4 months.',
        historyOfPresentIllness:
          '51-year-old female known diabetic for 8 years presenting with progressive bilateral glove-and-stocking burning paresthesia, nocturia (4-5x/night), and blurred vision. Scanned lab records show marked glycemic dysregulation (HbA1c 9.4%) and renal impairment (Creatinine 1.8 mg/dL, eGFR 48 mL/min).',
        pastMedicalHistory: ['Type 2 Diabetes Mellitus (8 yrs)', 'Essential Hypertension (5 yrs)'],
        medicationHistory: ['Tab Metformin 500mg BD (irregular adherence)', 'Tab Telmisartan 40mg OD'],
        allergies: ['No known drug allergies (NKDA)'],
        familyHistory: 'Both parents had Type 2 Diabetes.',
        socialHabits: 'Sedentary homemaker, vegetarian diet high in refined carbs.',
      },
      objective: {
        vitals: {
          bpSystolic: 148,
          bpDiastolic: 92,
          pulseRate: 78,
          spo2: 98,
          tempF: 98.6,
          respiratoryRate: 18,
          painScore: 6,
          bmi: 29.4,
        },
        physicalExamFindings: [
          'Bilateral 1+ pitting pedal edema up to lower tibia',
          'Decreased 10g monofilament sensation over bilateral great toes and metatarsal heads',
          'Vibration perception diminished at medial malleoli',
        ],
        extractedLabHighlights: SAMPLE_DOCUMENTS[1].labs,
        digitizedPastRx: [],
      },
      assessment: {
        provisionalDiagnoses: [
          {
            condition: 'Type 2 Diabetes Mellitus with Diabetic Polyneuropathy',
            icd10: 'E11.40',
            snomedCt: '237624004',
            confidence: 0.96,
            rationale: 'HbA1c 9.4% with classic symmetrical stocking paresthesia and reduced monofilament sensation.',
          },
          {
            condition: 'Diabetic Kidney Disease (Stage 3a CKD)',
            icd10: 'N18.3',
            snomedCt: '433144002',
            confidence: 0.91,
            rationale: 'Serum Creatinine 1.8 mg/dL with eGFR 48 mL/min in setting of long-standing diabetes.',
          },
        ],
        redFlagsIdentified: ['Renal impairment (eGFR < 60)', 'Severe glycemic decompensation (HbA1c 9.4%)'],
        clinicalRiskRating: 'MEDIUM',
      },
      plan: {
        proposedInvestigations: [
          'Urine Albumin-to-Creatinine Ratio (UACR)',
          'Fundus Fluorescein Angiography / Dilated Eye Exam (Diabetic Retinopathy Screen)',
          'Repeat Serum Electrolytes & Renal Function Panel',
          'Fasting Lipid Profile',
        ],
        medicationRecommendations: [
          {
            name: 'Tab Metformin XR',
            dosage: '500 mg',
            frequency: 'OD (Once daily with dinner)',
            duration: 'Dose adjusted for eGFR 48',
            instructions: 'Monitor renal function every 3 months',
            category: 'Allopathic',
          },
          {
            name: 'Tab Teneligliptin',
            dosage: '20 mg',
            frequency: 'OD (Once daily before breakfast)',
            duration: '90 days',
            instructions: 'Safe in renal impairment without dose adjustment',
            category: 'Allopathic',
          },
          {
            name: 'Cap Pregabalin',
            dosage: '75 mg',
            frequency: 'HS (Bedtime)',
            duration: '30 days',
            instructions: 'For neuropathic burning pain',
            category: 'Allopathic',
          },
          {
            name: 'Tab Telmisartan',
            dosage: '40 mg',
            frequency: 'OD (Morning)',
            duration: '90 days',
            instructions: 'Renoprotective anti-hypertensive',
            category: 'Allopathic',
          },
        ],
        lifestyleAndDietAdvice: [
          'Medical Nutrition Therapy: Low glycemic index diet, strict restriction of refined sugars',
          'Daily foot inspection using mirror, avoid walking barefoot',
          '30 minutes brisk walking daily as tolerated',
        ],
        triageDisposition: 'Fast-track OPD Consultation with Endocrinologist & Nephrology liaison',
        followUpInDays: 14,
      },
      metadata: {
        generatedAt: '2026-09-08T09:32:00Z',
        modelVersion: 'Med-Llama-3-8B-Indic + LangGraph Triage v3.1',
        mode: 'ALLOPATHIC',
        safetyLock: 'AI-Generated Triage Summary — Requires Clinician Verification',
        status: 'AI_DRAFT',
      },
    },
    fhirBundle: {},
  },
  {
    id: 'enc-2026-003',
    kioskId: 'KIOSK_AIIA_AYURVEDA_01',
    mode: 'AYUSH',
    language: 'hi',
    createdAt: '2026-09-08T09:45:00Z',
    status: 'WAITING',
    patient: {
      abhaNumber: '73-2940-1928-3019',
      abhaAddress: 'vikram.joshi42@abdm',
      name: 'Vikramaditya Joshi',
      gender: 'MALE',
      age: 42,
      dob: '1984-03-15',
      mobile: '+91 99887 76655',
      pinCode: '302001',
      state: 'Rajasthan',
      district: 'Jaipur',
      photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
      authMethod: 'QR_SCAN',
      verified: true,
      queueToken: 'OPD-P3-1204',
      queueNumber: 3,
      registeredAt: '2026-09-08T09:45:00Z',
    },
    redFlag: {
      isTriggered: false,
      level: 'NORMAL',
      triagePriority: 'P3_ROUTINE',
      triggeredRules: [],
      immediateAction: 'Routine AYUSH OPD consultation token allocated. Please proceed to Kaya Chikitsa Cabin 3.',
      emergencyTokenCode: 'OPD-P3-1204',
      timestamp: '2026-09-08T09:47:00Z',
      acknowledgedByDoctor: true,
    },
    ayush: {
      prakriti: 'Vata-Pitta',
      vikriti: 'Vata Vriddhi with Sama Pitta & Agnimandya',
      sara: 'Mamsa-Asthi Madhyama Sara',
      samhanana: 'Medium / Madhyama',
      pramana: 'Madhyama Pramana (Normal BMI 23.8)',
      satmya: 'Shadrasa Satmya, predominantly Katu-Lavana habituation',
      sattva: 'Madhyama (Moderate)',
      aharaShakti: {
        abhyavaharana: 'Moderate',
        jaranaShakti: 'Vishamagni',
      },
      vyayamaShakti: 'Moderate',
      vaya: 'Madhyama (Adult)',
      ashtavidha: {
        nadi: 'Sarpa-gati predominant with intermittent Manduka-gati (Vata-Pitta Nadi)',
        mutra: 'Peeta-varna (pale yellow), 5-6 times/day, Avila (clear)',
        mala: 'Vibandha (constipation / irregular dry stools), sashabda vata-pravritti',
        jihva: 'Sama Jihva (white coating at posterior third indicating Ama)',
        shabda: 'Spashta, gambhira',
        sparsha: 'Sheeta-ruksha in extremities, ushna in trunk',
        druk: 'Alpa-ruksha, slight conjunctival congestion',
        akruti: 'Krisha-madhyama gaatra',
      },
      aharaVihara: {
        dietHabits: 'Irregular eating times (Vishamashana), excessive consumption of dry/spicy snacks, tea 5 cups/day',
        sleepPattern: 'Alpa-nidra (difficulty initiating sleep, waking at 3 AM due to racing thoughts)',
        dailyRoutine: 'Desk job, prolonged sitting, lack of daily Abhyanga or physical exercise',
      },
    },
    scannedDocuments: [parseDocumentScan('doc-ayush-03')],
    soapNote: {
      subjective: {
        chiefComplaint: 'Chronic bloating, Vishamagni (irregular digestion), constipation, joint stiffness and restless sleep for 8 months.',
        historyOfPresentIllness:
          '42-year-old software architect presenting with classical Vata-Pitta Prakopa: gas distension after meals, hard stools once in 2-3 days, bilateral knee crepitus without frank swelling, and unrefreshing sleep. Reports high occupational stress and erratic meal schedules (Adhyashana / Vishamashana).',
        pastMedicalHistory: ['GERD / Amlapitta (2 yrs)', 'Cervical Spondylosis (mild)'],
        medicationHistory: ['Occasional OTC antacids and laxative powders'],
        allergies: ['NKDA'],
        familyHistory: 'Mother had Sandhivata (Osteoarthritis).',
        socialHabits: 'Non-smoker, non-drinker, high caffeine intake.',
      },
      objective: {
        vitals: {
          bpSystolic: 122,
          bpDiastolic: 78,
          pulseRate: 72,
          spo2: 99,
          tempF: 98.4,
          respiratoryRate: 16,
          painScore: 4,
          bmi: 23.8,
        },
        physicalExamFindings: [
          'Abdominal palpation: Tympanitic note over left iliac fossa with mild tenderness on deep palpation (Vata-Anaha)',
          'Tongue: Sama coating at root of tongue',
          'Joints: Mild bilateral crepitus over knee joints, no local rise of temperature',
        ],
        extractedLabHighlights: [],
        digitizedPastRx: SAMPLE_DOCUMENTS[2].meds,
      },
      assessment: {
        provisionalDiagnoses: [
          {
            condition: 'Vata-Pitta Prakopa with Agnimandya and Koshtagata Vata',
            icd10: 'K30',
            snomedCt: 'AY-DIAG-01',
            confidence: 0.95,
            rationale: 'Ashtavidha Pariksha confirms Sama Jihva, Vibandha, Sarpa Nadi and Vishamagni secondary to irregular Ahara-Vihara.',
          },
          {
            condition: 'Sandhivata (Early Degenerative Arthropathy / Osteoarthritis)',
            icd10: 'M17.9',
            snomedCt: '239872002',
            confidence: 0.89,
            rationale: 'Mild crepitus and joint stiffness aggravated by cold weather and dry diet.',
          },
        ],
        ayushDiagnosis: {
          vyadhi: 'Koshtagata Vata / Grahani Dosha & Sandhivata',
          doshaDushya: 'Vata (Vyana & Samana) + Pitta (Pachaka) Dushti with Rasavaha & Annavaha Srotas',
          samprapti: 'Agnimandya -> Ama formation -> Srotorodha -> Vata Prakopa manifesting as Vibandha & Sandhi-shoola.',
        },
        redFlagsIdentified: [],
        clinicalRiskRating: 'LOW',
      },
      plan: {
        proposedInvestigations: [
          'Routine Stool Examination (for occult blood & parasite ova)',
          'Serum Vitamin D3 & B12 levels',
          'Bilateral Knee X-ray AP & Lateral views (if crepitus worsens)',
        ],
        medicationRecommendations: [
          {
            name: 'Triphala Guggulu',
            dosage: '2 tablets (500mg)',
            frequency: 'BD (Twice daily)',
            duration: '45 days',
            instructions: 'Take with warm water before food for Amapachana and Vatanulomana',
            category: 'AYUSH',
          },
          {
            name: 'Dashamoola Kwatha',
            dosage: '20 ml',
            frequency: 'BD (Twice daily)',
            duration: '30 days',
            instructions: 'Mix with 40ml warm water, take 30 mins before food (Vata shamana)',
            category: 'AYUSH',
          },
          {
            name: 'Ashwagandhadi Lehyam',
            dosage: '10 g (1 teaspoon)',
            frequency: 'HS (Bedtime)',
            duration: '30 days',
            instructions: 'Take with warm cow milk at bedtime for Rasayana and Sukh-nidra',
            category: 'AYUSH',
          },
          {
            name: 'Ksheerabala Taila (101 Avartita)',
            dosage: '10 drops',
            frequency: 'OD (Night)',
            duration: '21 days',
            instructions: 'Take with warm milk for nervous rejuvenation and joint lubrication',
            category: 'AYUSH',
          },
        ],
        lifestyleAndDietAdvice: [
          'Ahara: Warm, freshly prepared, easily digestible meals (Laghu Ahara) with 1 tsp Cow Ghee. Avoid dry, refrigerated, stale, and deep-fried foods.',
          'Vihara: Daily Sarvanga Abhyanga (warm Sesame oil massage) followed by warm water bath. Practice Nadi Shodhana Pranayama 15 mins daily.',
          'Panchakarma: Recommended for Matra Basti (mild herbal oil enema) course after Amapachana phase.',
        ],
        triageDisposition: 'Routine AYUSH Consultation & Panchakarma wellness scheduling',
        followUpInDays: 21,
      },
      metadata: {
        generatedAt: '2026-09-08T09:47:00Z',
        modelVersion: 'Med-Llama-3-8B-AYUSH-Ontology v3.1',
        mode: 'AYUSH',
        safetyLock: 'AI-Generated Triage Summary — Requires Clinician Verification',
        status: 'AI_DRAFT',
      },
    },
    fhirBundle: {},
  },
];

// Hydrate initial FHIR bundles
INITIAL_PATIENTS.forEach((p) => {
  p.fhirBundle = generateFhirR4Bundle(p);
});
