import type { LanguageInfo, LanguageCode } from '../types';
export type { LanguageCode };

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', voiceLangCode: 'hi-IN', flag: '🇮🇳' },
  { code: 'en', label: 'English', nativeLabel: 'English', voiceLangCode: 'en-IN', flag: '🌐' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', voiceLangCode: 'mr-IN', flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', voiceLangCode: 'ta-IN', flag: '🇮🇳' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', voiceLangCode: 'te-IN', flag: '🇮🇳' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', voiceLangCode: 'bn-IN', flag: '🇮🇳' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ', voiceLangCode: 'kn-IN', flag: '🇮🇳' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી', voiceLangCode: 'gu-IN', flag: '🇮🇳' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം', voiceLangCode: 'ml-IN', flag: '🇮🇳' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ', voiceLangCode: 'pa-IN', flag: '🇮🇳' },
  { code: 'or', label: 'Odia', nativeLabel: 'ଓଡ଼ିଆ', voiceLangCode: 'or-IN', flag: '🇮🇳' },
  { code: 'as', label: 'Assamese', nativeLabel: 'অসমীয়া', voiceLangCode: 'as-IN', flag: '🇮🇳' },
  { code: 'ur', label: 'Urdu', nativeLabel: 'اردو', voiceLangCode: 'ur-IN', flag: '🇮🇳' },
];

export const UI_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  hi: {
    welcomeTitle: 'आयुष्मान भारत - आभा प्रो ओपीडी कियोस्क',
    welcomeSubtitle: 'कृपया अपनी भाषा चुनें और अपनी आभा आईडी स्कैन करें',
    scanAbha: 'आभा कार्ड स्कैन करें',
    enterMobile: 'मोबाइल / आभा नंबर दर्ज करें',
    voicePrompt: 'माइक दबाएं और अपनी समस्या बताएं',
    listening: 'सुन रहे हैं... कृपया बोलें',
    speakNow: 'बोलें...',
    selectBodyPart: 'शरीर का वह अंग चुनें जहां परेशानी है',
    painLevel: 'दर्द का स्तर बताएं (1 से 10)',
    allopathicMode: 'एलोपैथिक जांच (SOCRATES)',
    ayushMode: 'आयुष एवं पंचकर्म (दशविध परीक्षा)',
    scanDocuments: 'पुरानी पर्ची या लैब रिपोर्ट स्कैन करें',
    processingOcr: 'दस्तावेज़ की जांच हो रही है (AI TrOCR + LayoutLMv3)...',
    redFlagAlert: 'आपातकालीन चेतावनी: कृपया तुरंत आपातकालीन कक्ष (ER) में जाएं!',
    printToken: 'ओपीडी कतार टोकन प्रिंट करें',
    tokenNumber: 'टोकन संख्या',
    emergencyToken: 'तत्काल आपातकालीन टोकन',
    consentText: 'मैं आभा स्वास्थ्य रिकॉर्ड साझा करने और एआई ओपीडी ट्राइएज के लिए सहमति देता/देती हूँ।',
    acceptConsent: 'सहमति दें और आगे बढ़ें',
    next: 'आगे बढ़ें',
    back: 'पीछे जाएं',
    confirm: 'पुष्टि करें',
  },
  en: {
    welcomeTitle: 'Ayushman Bharat - ABHA PRO OPD Kiosk',
    welcomeSubtitle: 'Please select your language and scan your ABHA ID',
    scanAbha: 'Scan ABHA Card / QR',
    enterMobile: 'Enter Mobile / ABHA Number',
    voicePrompt: 'Tap microphone and speak your symptoms',
    listening: 'Listening... Please speak now',
    speakNow: 'Speak now...',
    selectBodyPart: 'Touch the body part where you feel pain or discomfort',
    painLevel: 'Rate your pain severity (1 to 10)',
    allopathicMode: 'Allopathic Protocol (SOCRATES + ROS)',
    ayushMode: 'AYUSH & Panchakarma (Dashavidha Pariksha)',
    scanDocuments: 'Feed / Scan Physical Prescriptions or Lab Reports',
    processingOcr: 'Digitizing medical documents via TrOCR & LayoutLMv3...',
    redFlagAlert: 'EMERGENCY RED-FLAG: High risk detected! Proceed directly to Triage Desk.',
    printToken: 'Print OPD Queue Token',
    tokenNumber: 'Token Number',
    emergencyToken: 'EMERGENCY RED PRIORITY TOKEN',
    consentText: 'I grant consent to share health records via ABDM for AI OPD triage synthesis.',
    acceptConsent: 'Accept & Proceed',
    next: 'Next',
    back: 'Back',
    confirm: 'Confirm',
  },
  mr: {
    welcomeTitle: 'आयुष्मान भारत - आभा प्रो ओपीडी किओस्क',
    welcomeSubtitle: 'कृपया आपली भाषा निवडा आणि आभा आयडी स्कॅन करा',
    scanAbha: 'आभा कार्ड स्कॅन करा',
    enterMobile: 'मोबाईल / आभा क्रमांक टाका',
    voicePrompt: 'माईक दाबा आणि लक्षणे सांगा',
    listening: 'ऐकत आहे... कृपया बोला',
    speakNow: 'बोला...',
    selectBodyPart: 'त्रास होत असलेला शरीराचा भाग निवडा',
    painLevel: 'वेदना तीव्रता निवडा (१ ते १०)',
    allopathicMode: 'अ‍ॅलोपॅथी पद्धत (SOCRATES)',
    ayushMode: 'आयुष आणि दशविध परीक्षा',
    scanDocuments: 'जुनी प्रिस्क्रिप्शन किंवा लॅब रिपोर्ट स्कॅन करा',
    processingOcr: 'कागदपत्र डिजिटायझेशन सुरू आहे...',
    redFlagAlert: 'तातडीची चेतावणी: कृपया त्वरित इमर्जन्सी वॉर्डमध्ये जा!',
    printToken: 'ओपीडी टोकन प्रिंट करा',
    tokenNumber: 'टोकन क्रमांक',
    emergencyToken: 'तातडीचे रेड टोकन',
    consentText: 'मी आभा आरोग्य नोंदी वापरण्यास संमती देतो/देते.',
    acceptConsent: 'संमती द्या आणि पुढे चला',
    next: 'पुढे',
    back: 'मागे',
    confirm: 'खात्री करा',
  },
  ta: {
    welcomeTitle: 'ஆயுஷ்மான் பாரத் - ஆபா புரோ ஓபிடி கியோஸ்க்',
    welcomeSubtitle: 'உங்கள் மொழியைத் தேர்ந்தெடுத்து ஆபா ஐடியை ஸ்கேன் செய்யவும்',
    scanAbha: 'ஆபா கார்டை ஸ்கேன் செய்யவும்',
    enterMobile: 'மொபைல் / ஆபா எண்ணை உள்ளிடவும்',
    voicePrompt: 'மைக்கை அழுத்தி அறிகுறிகளைக் கூறவும்',
    listening: 'கேட்கிறது... பேசவும்',
    speakNow: 'பேசவும்...',
    selectBodyPart: 'பிரச்சனை உள்ள உடல் பகுதியைத் தொடவும்',
    painLevel: 'வலி அளவை தேர்வு செய்யவும் (1 முதல் 10)',
    allopathicMode: 'அலோபதி முறை (SOCRATES)',
    ayushMode: 'ஆயுஷ் முறை (தசவித பரீட்சை)',
    scanDocuments: 'மருத்துவ சீட்டு / ஆய்வக அறிக்கையை ஸ்கேன் செய்யவும்',
    processingOcr: 'ஆவணங்கள் டிஜிட்டல் செய்யப்படுகின்றன...',
    redFlagAlert: 'அவசர எச்சரிக்கை: தயவுசெய்து உடனடியாக அவசர சிகிச்சைப் பிரிவுக்குச் செல்லவும்!',
    printToken: 'டோக்கன் அச்சிடவும்',
    tokenNumber: 'டோக்கன் எண்',
    emergencyToken: 'அவசர சிவப்பு டோக்கன்',
    consentText: 'ஆபா மருத்துவ பதிவுகளை பகிர நான் ஒப்புதல் அளிக்கிறேன்.',
    acceptConsent: 'ஒப்புதல் அளித்து தொடரவும்',
    next: 'அடுத்து',
    back: 'பின்செல்',
    confirm: 'உறுதி செய்',
  },
  te: {
    welcomeTitle: 'ఆయుష్మాన్ భారత్ - ఆభా ప్రో ఓపీడీ కియోస్క్',
    welcomeSubtitle: 'మీ భాషను ఎంచుకోండి మరియు ఆభా ఐడీని స్కాన్ చేయండి',
    scanAbha: 'ఆభా కార్డును స్కాన్ చేయండి',
    enterMobile: 'మొబైల్ / ఆభా సంఖ్యను నమోదు చేయండి',
    voicePrompt: 'మైక్ నొక్కి మీ సమస్యను చెప్పండి',
    listening: 'వింటున్నాము... మాట్లాడండి',
    speakNow: 'మాట్లాడండి...',
    selectBodyPart: 'సమస్య ఉన్న శరీర భాగాన్ని ఎంచుకోండి',
    painLevel: 'నొప్పి తీవ్రతను ఎంచుకోండి (1 నుండి 10)',
    allopathicMode: 'అల్లోపతి విధానం (SOCRATES)',
    ayushMode: 'ఆయుష్ విధానం (దశవిధ పరీక్ష)',
    scanDocuments: 'పాత మందుల చీటీ / ల్యాబ్ రిపోర్టును స్కాన్ చేయండి',
    processingOcr: 'పత్రాల గుర్తింపు జరుగుతోంది...',
    redFlagAlert: 'అత్యవసర హెచ్చరిక: వెంటనే ఎమర్జెన్సీ విభాగానికి వెళ్ళండి!',
    printToken: 'ఓపీడీ టోకెన్ ముద్రించండి',
    tokenNumber: 'టోకెన్ సంఖ్య',
    emergencyToken: 'ఎమర్జెన్సీ రెడ్ టోకెన్',
    consentText: 'నేను ఆభా ఆరోగ్య సమాచార వినియోగానికి సమ్మతిస్తున్నాను.',
    acceptConsent: 'సమ్మతించి కొనసాగండి',
    next: 'తరువాత',
    back: 'వెనుకకు',
    confirm: 'నిర్ధారించండి',
  },
  bn: {
    welcomeTitle: 'আয়ুষ্মান ভারত - আভা প্রো ওপিডি কিয়স্ক',
    welcomeSubtitle: 'আপনার ভাষা বেছে নিন এবং আভা আইডি স্ক্যান করুন',
    scanAbha: 'আভা কার্ড স্ক্যান করুন',
    enterMobile: 'মোবাইল / আভা নম্বর লিখুন',
    voicePrompt: 'মাইক চাপুন এবং আপনার সমস্যার কথা বলুন',
    listening: 'শুনছি... অনুগ্রহ করে বলুন',
    speakNow: 'বলুন...',
    selectBodyPart: 'শরীরের আক্রান্ত অংশ নির্বাচন করুন',
    painLevel: 'ব্যথার মাত্রা নির্ধারণ করুন (১ থেকে ১০)',
    allopathicMode: 'অ্যালোপ্যাথিক প্রোটোকল (SOCRATES)',
    ayushMode: 'আয়ুশ প্রোটোকল (দশবিধ পরীক্ষা)',
    scanDocuments: 'পুরোনো প্রেসক্রিপশন বা ল্যাব রিপোর্ট স্ক্যান করুন',
    processingOcr: 'নথি প্রক্রিয়াধীন...',
    redFlagAlert: 'জরুরি সতর্কতা: অবিলম্বে জরুরি বিভাগে যোগাযোগ করুন!',
    printToken: 'ওপিডি টোকেন প্রিন্ট করুন',
    tokenNumber: 'টোকেন নম্বর',
    emergencyToken: 'জরুরি রেড টোকেন',
    consentText: 'আমি আভা স্বাস্থ্য তথ্য শেয়ার করতে সম্মতি দিচ্ছি।',
    acceptConsent: 'সম্মতি দিন ও এগিয়ে যান',
    next: 'পরবর্তী',
    back: 'পেছনে',
    confirm: 'নিশ্চিত করুন',
  },
  kn: {
    welcomeTitle: 'ಆಯುಷ್ಮಾನ್ ಭಾರತ್ - ಆಭಾ ಪ್ರೊ ಒಪಿಡಿ ಕಿಯೋಸ್ಕ್',
    welcomeSubtitle: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ ಮತ್ತು ಆಭಾ ಐಡಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    scanAbha: 'ಆಭಾ ಕಾರ್ಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    enterMobile: 'ಮೊಬೈಲ್ / ಆಭಾ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    voicePrompt: 'ಮೈಕ್ ಒತ್ತಿ ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಮಾತನಾಡಿ',
    listening: 'ಆಲಿಸಲಾಗುತ್ತಿದೆ... ಮಾತನಾಡಿ',
    speakNow: 'ಮಾತನಾಡಿ...',
    selectBodyPart: 'ತೊಂದರೆ ಇರುವ ದೇಹದ ಭಾಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    painLevel: 'ನೋವಿನ ತೀವ್ರತೆ (1 ರಿಂದ 10)',
    allopathicMode: 'ಅಲೋಪತಿ ವಿಧಾನ (SOCRATES)',
    ayushMode: 'ಆಯುಷ್ ವಿಧಾನ (ದಶವಿಧ ಪರೀಕ್ಷೆ)',
    scanDocuments: 'ಹಳೆಯ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ / ಲ್ಯಾಬ್ ವರದಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    processingOcr: 'ದಾಖಲೆ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...',
    redFlagAlert: 'ತುರ್ತು ಎಚ್ಚರಿಕೆ: ದಯವಿಟ್ಟು ತಕ್ಷಣ ತುರ್ತು ಚಿಕಿತ್ಸಾ ವಿಭಾಗಕ್ಕೆ ತೆರಳಿ!',
    printToken: 'ಟೋಕನ್ ಮುದ್ರಿಸಿ',
    tokenNumber: 'ಟೋಕನ್ ಸಂಖ್ಯೆ',
    emergencyToken: 'ತುರ್ತು ರೆಡ್ ಟೋಕನ್',
    consentText: 'ಆಭಾ ಆರೋಗ್ಯ ದಾಖಲೆ ಹಂಚಿಕೊಳ್ಳಲು ನಾನು ಸಮ್ಮತಿಸುತ್ತೇನೆ.',
    acceptConsent: 'ಸಮ್ಮತಿಸಿ ಮುಂದುವರಿಯಿರಿ',
    next: 'ಮುಂದೆ',
    back: 'ಹಿಂದೆ',
    confirm: 'ದೃಢೀಕರಿಸಿ',
  },
  gu: {
    welcomeTitle: 'આયુષ્માન ભારત - આભા પ્રો ઓપીડી કિઓસ્ક',
    welcomeSubtitle: 'કૃપા કરીને તમારી ભાષા પસંદ કરો અને આભા આઈડી સ્કેન કરો',
    scanAbha: 'આભા કાર્ડ સ્કેન કરો',
    enterMobile: 'મોબાઇલ / આભા નંબર દાખલ કરો',
    voicePrompt: 'માઈક દબાવો અને લક્ષણો જણાવો',
    listening: 'સાંભળી રહ્યા છીએ... બોલો',
    speakNow: 'બોલો...',
    selectBodyPart: 'તકલીફ વાળો શરીરનો ભાગ પસંદ કરો',
    painLevel: 'દુખાવાની તીવ્રતા (૧ થી ૧૦)',
    allopathicMode: 'એલોપેથી પદ્ધતિ (SOCRATES)',
    ayushMode: 'આયુષ પદ્ધતિ (દશવિધ પરીક્ષા)',
    scanDocuments: 'જૂની દવાઓની ચિઠ્ઠી / લેબ રિપોર્ટ સ્કેન કરો',
    processingOcr: 'દસ્તાવેજ સ્કેનિંગ શરૂ છે...',
    redFlagAlert: 'કટોકટી ચેતવણી: કૃપા કરીને તાત્કાલિક ઇમરજન્સી રૂમમાં જાઓ!',
    printToken: 'ઓપીડી ટોકન પ્રિન્ટ કરો',
    tokenNumber: 'ટોકન નંબર',
    emergencyToken: 'ઇમરજન્સી રેડ ટોકન',
    consentText: 'હું આભા હેલ્થ રેકોર્ડ શેર કરવા સંમતિ આપું છું.',
    acceptConsent: 'સંમતિ આપો અને આગળ વધો',
    next: 'આગળ',
    back: 'પાછળ',
    confirm: 'પુષ્ટિ કરો',
  },
  ml: {
    welcomeTitle: 'ആയുഷ്മാൻ ഭാരത് - ആഭ പ്രോ ഒപിഡി കിയോസ്ക്',
    welcomeSubtitle: 'ഭാഷ തിരഞ്ഞെടുത്ത് ആഭ ഐഡി സ്കാൻ ചെയ്യുക',
    scanAbha: 'ആഭ കാർഡ് സ്കാൻ ചെയ്യുക',
    enterMobile: 'മൊബൈൽ / ആഭ നമ്പർ നൽകുക',
    voicePrompt: 'മൈക്ക് അമർത്തി ലക്ഷണങ്ങൾ പറയുക',
    listening: 'കേൾക്കുന്നു... സംസാരിക്കൂ',
    speakNow: 'സംസാരിക്കൂ...',
    selectBodyPart: 'വേദനയുള്ള ശരീരഭാഗം തിരഞ്ഞെടുക്കുക',
    painLevel: 'വേദനയുടെ തീവ്രത (1 മുതൽ 10 വരെ)',
    allopathicMode: 'അലോപ്പതി രീതി (SOCRATES)',
    ayushMode: 'ആയുഷ് രീതി (ദശവിധ പരീക്ഷ)',
    scanDocuments: 'പഴയ കുറിപ്പടിയോ ലാബ് റിപ്പോർട്ടോ സ്കാൻ ചെയ്യുക',
    processingOcr: 'രേഖകൾ പ്രോസസ്സ് ചെയ്യുന്നു...',
    redFlagAlert: 'അടിയന്തിര മുന്നറിയിപ്പ്: ദയവായി ഉടൻ എമർജൻസി വിഭാഗത്തിലേക്ക് പോകുക!',
    printToken: 'ടോക്കൺ പ്രിന്റ് ചെയ്യുക',
    tokenNumber: 'ടോക്കൺ നമ്പർ',
    emergencyToken: 'അടിയന്തര റെഡ് ടോക്കൺ',
    consentText: 'ആഭ വിവരങ്ങൾ പങ്കിടാൻ ഞാൻ സമ്മതിക്കുന്നു.',
    acceptConsent: 'സമ്മതിച്ചു മുന്നോട്ട് പോകുക',
    next: 'അടുത്തത്',
    back: 'പിന്നോട്ട്',
    confirm: 'സ്ഥിരീകരിക്കുക',
  },
  pa: {
    welcomeTitle: 'ਆਯੁਸ਼ਮਾਨ ਭਾਰਤ - ਆਭਾ ਪ੍ਰੋ ਓਪੀਡੀ ਕਿਓਸਕ',
    welcomeSubtitle: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ ਅਤੇ ਆਭਾ ਆਈਡੀ ਸਕੈਨ ਕਰੋ',
    scanAbha: 'ਆਭਾ ਕਾਰਡ ਸਕੈਨ ਕਰੋ',
    enterMobile: 'ਮੋਬਾਈਲ / ਆਭਾ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    voicePrompt: 'ਮਾਈਕ ਦਬਾਓ ਅਤੇ ਆਪਣੀ ਤਕਲੀਫ ਦੱਸੋ',
    listening: 'ਸੁਣ ਰਹੇ ਹਾਂ... ਬੋਲੋ',
    speakNow: 'ਬੋਲੋ...',
    selectBodyPart: 'ਦਰਦ ਵਾਲਾ ਸਰੀਰ ਦਾ ਹਿੱਸਾ ਚੁਣੋ',
    painLevel: 'ਦਰਦ ਦਾ ਪੱਧਰ (1 ਤੋਂ 10)',
    allopathicMode: 'ਐਲੋਪੈਥਿਕ ਪ੍ਰਣਾਲੀ (SOCRATES)',
    ayushMode: 'ਆਯੂਸ਼ ਪ੍ਰਣਾਲੀ (ਦਸ਼ਵਿਧ ਪ੍ਰੀਖਿਆ)',
    scanDocuments: 'ਪੁਰਾਣੀ ਪਰਚੀ ਜਾਂ ਲੈਬ ਰਿਪੋਰਟ ਸਕੈਨ ਕਰੋ',
    processingOcr: 'ਦਸਤਾਵੇਜ਼ ਦੀ ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ...',
    redFlagAlert: 'ਐਮਰਜੈਂਸੀ ਚੇਤਾਵਨੀ: ਤੁਰੰਤ ਐਮਰਜੈਂਸੀ ਰੂਮ ਵਿੱਚ ਜਾਓ!',
    printToken: 'ਓਪੀਡੀ ਟੋਕਨ ਪ੍ਰਿੰਟ ਕਰੋ',
    tokenNumber: 'ਟੋਕਨ ਨੰਬਰ',
    emergencyToken: 'ਐਮਰਜੈਂਸੀ ਰੈੱਡ ਟੋਕਨ',
    consentText: 'ਮੈਂ ਆਭਾ ਰਿਕਾਰਡ ਸਾਂਝੇ ਕਰਨ ਦੀ ਸਹਿਮਤੀ ਦਿੰਦਾ ਹਾਂ।',
    acceptConsent: 'ਸਹਿਮਤੀ ਦਿਓ ਅਤੇ ਅੱਗੇ ਵਧੋ',
    next: 'ਅੱਗੇ',
    back: 'ਪਿੱਛੇ',
    confirm: 'ਪੁਸ਼ਟੀ ਕਰੋ',
  },
  or: {
    welcomeTitle: 'ଆୟୁଷ୍ମାନ ଭାରତ - ଆଭା ପ୍ରୋ ଓପିଡି କିଓସ୍କ',
    welcomeSubtitle: 'ଦୟାକରି ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ ଏବଂ ଆଭା ଆଇଡି ସ୍କାନ କରନ୍ତୁ',
    scanAbha: 'ଆଭା କାର୍ଡ ସ୍କାନ କରନ୍ତୁ',
    enterMobile: 'ମୋବାଇଲ୍ / ଆଭା ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ',
    voicePrompt: 'ମାଇକ୍ ଦବାନ୍ତୁ ଏବଂ ସମସ୍ୟା କୁହନ୍ତୁ',
    listening: 'ଶୁଣୁଛୁ... କୁହନ୍ତୁ',
    speakNow: 'କୁହନ୍ତୁ...',
    selectBodyPart: 'ଅସୁବିଧା ଥିବା ଶରୀର ଅଂଶ ବାଛନ୍ତୁ',
    painLevel: 'ଯନ୍ତ୍ରଣା ସ୍ତର (୧ ରୁ ୧୦)',
    allopathicMode: 'ଆଲୋପାଥିକ ପଦ୍ଧତି (SOCRATES)',
    ayushMode: 'ଆୟୁଷ ପଦ୍ଧତି (ଦଶବିଧ ପରୀକ୍ଷା)',
    scanDocuments: 'ପୁରୁଣା ପ୍ରେସକ୍ରିପସନ୍ / ଲ୍ୟାବ୍ ରିପୋର୍ଟ ସ୍କାନ କରନ୍ତୁ',
    processingOcr: 'ଦଲିଲ ଯାଞ୍ଚ ହେଉଛି...',
    redFlagAlert: 'ଜରୁରୀକାଳୀନ ଚେତାବନୀ: ତୁରନ୍ତ ଜରୁରୀକାଳୀନ ବିଭାଗକୁ ଯାଆନ୍ତୁ!',
    printToken: 'ଓପିଡି ଟୋକନ୍ ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
    tokenNumber: 'ଟୋକନ୍ ନମ୍ବର',
    emergencyToken: 'ଜରୁରୀକାଳୀନ ରେଡ୍ ଟୋକନ୍',
    consentText: 'ମୁଁ ଆଭା ସ୍ୱାସ୍ଥ୍ୟ ତଥ୍ୟ ବ୍ୟବହାର ପାଇଁ ସମ୍ମତି ଦେଉଛି।',
    acceptConsent: 'ସମ୍ମତି ଦିଅନ୍ତୁ ଓ ଆଗକୁ ବଢନ୍ତୁ',
    next: 'ଆଗକୁ',
    back: 'ପଛକୁ',
    confirm: 'ନିଶ୍ଚିତ କରନ୍ତୁ',
  },
  as: {
    welcomeTitle: 'আয়ুষ্মান ভাৰত - আভা প্ৰ\' অ\'পিডি কিঅ\'স্ক',
    welcomeSubtitle: 'অনুগ্ৰহ কৰি ভাষা বাছনি কৰক আৰু আভা আইডি স্কেন কৰক',
    scanAbha: 'আভা কাৰ্ড স্কেন কৰক',
    enterMobile: 'ম\'বাইল / আভা নম্বৰ দিয়ক',
    voicePrompt: 'মাইক টিপি লক্ষণবোৰ কওক',
    listening: 'শুনি আছোঁ... কওক',
    speakNow: 'কওক...',
    selectBodyPart: 'সমস্যা থকা দেহৰ অংগ বাছক',
    painLevel: 'বিষৰ মাত্ৰা (১ ৰ পৰা ১০)',
    allopathicMode: 'এলোপেথিক পদ্ধতি (SOCRATES)',
    ayushMode: 'আয়ুষ পদ্ধতি (দশবিধ পৰীক্ষা)',
    scanDocuments: 'পুৰণি প্ৰেছক্ৰিপশ্বন বা লেব ৰিপ\'ৰ্ট স্কেন কৰক',
    processingOcr: 'নথি প্ৰক্ৰিয়াকৰণ চলি আছে...',
    redFlagAlert: 'জৰুৰী সতৰ্কবাৰ্তা: অনুগ্ৰহ কৰি ততাতৈয়াকৈ জৰুৰীকালীন কোঠালৈ যাওক!',
    printToken: 'টোকেন প্ৰিণ্ট কৰক',
    tokenNumber: 'টোকেন নম্বৰ',
    emergencyToken: 'জৰুৰীকালীন ৰেড টোকেন',
    consentText: 'মই আভা তথ্য ভাগ-বতৰা কৰিবলৈ সন্মতি দিছোঁ।',
    acceptConsent: 'সন্মতি দিয়ক আৰু আগবাঢ়ক',
    next: 'পৰৱৰ্তী',
    back: 'পিছলৈ',
    confirm: 'নিশ্চিত কৰক',
  },
  ur: {
    welcomeTitle: 'آیوشمان بھارت - آبھا پرو او پی ڈی کیوسک',
    welcomeSubtitle: 'براہ کرم اپنی زبان منتخب کریں اور آبھا آئی ڈی اسکین کریں',
    scanAbha: 'آبھا کارڈ اسکین کریں',
    enterMobile: 'موبائل / آبھا نمبر درج کریں',
    voicePrompt: 'مائیک دبائیں اور اپنی علامات بتائیں',
    listening: 'سن رہے ہیں... بولیں',
    speakNow: 'بولیں...',
    selectBodyPart: 'تکلیف کا جسمانی حصہ منتخب کریں',
    painLevel: 'درد کی شدت (1 تا 10)',
    allopathicMode: 'ایلوپیتھک طریقہ (SOCRATES)',
    ayushMode: 'آیوش طریقہ (دش ودھ پریکشا)',
    scanDocuments: 'پرانا نسخہ یا لیب رپورٹ اسکین کریں',
    processingOcr: 'دستاویزات کی ڈیجیٹائزیشن جاری ہے...',
    redFlagAlert: 'ہنگامی الرٹ: فوری طور پر ایمرجنسی وارڈ میں تشریف لے جائیں!',
    printToken: 'او پی ڈی ٹوکن پرنٹ کریں',
    tokenNumber: 'ٹوکن نمبر',
    emergencyToken: 'ہنگامی ریڈ ٹوکن',
    consentText: 'میں آبھا ہیلتھ ریکارڈ شیئر کرنے کی رضامندی دیتا/دیتی ہوں۔',
    acceptConsent: 'رضامندی دیں اور آگے بڑھیں',
    next: 'آگے',
    back: 'پیچھے',
    confirm: 'تصدیق کریں',
  },
};

export function speakText(text: string, langCode: LanguageCode = 'hi'): Promise<void> {
  return new Promise((resolve) => {
    if (!('speechSynthesis' in window)) {
      resolve();
      return;
    }
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    const langInfo = SUPPORTED_LANGUAGES.find((l) => l.code === langCode);
    utterance.lang = langInfo?.voiceLangCode || 'hi-IN';
    utterance.rate = 0.95;
    utterance.pitch = 1.0;
    utterance.onend = () => resolve();
    utterance.onerror = () => resolve();
    window.speechSynthesis.speak(utterance);
  });
}
